version: '3.7'

	  
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/umbrel/umbrel/my-configs/resiliosync-config:/config
      - /home/umbrel/umbrel/data/storage/resiliosync/downloads:/downloads
      - /home/umbrel/umbrel:/sync
    ports:
      - 8888:8888
      - 55555:55555